CREATE TABLE quote (
	id INT NOT NULL AUTO_INCREMENT,
	day VARCHAR(255) DEFAULT NULL,
    room VARCHAR(255) DEFAULT NULL,
	detail TEXT,
	author_id INT DEFAULT NULL,
	PRIMARY KEY (id),
	CONSTRAINT FK_284329 FOREIGN KEY (author_id) REFERENCES author(id) ON UPDATE CASCADE ON DELETE CASCADE
);


CREATE TABLE author (
	id INT NOT NULL AUTO_INCREMENT,
	fname VARCHAR(255) NOT NULL,
	PRIMARY KEY (id)
);